server {
  listen 80 default_server;
  listen [::]:80 default_server;

  server_name api.dev-orcha.com;

  # redirect any request to root domain to the marketing website
  server_name dev-orcha.com;
  if ($host = dev-orcha.com) {
      return 301 https://www.$host$request_uri;
  }

  location / {
    # If you want basic auth protection
    # auth_basic “Restricted”;
    # auth_basic_user_file /etc/apache2/.htpasswd;

    # First attempt to serve request as file, then
    # as directory, then fall back to displaying a 404.
    proxy_pass http://localhost:4000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-NginX-Proxy true;
    proxy_cache_bypass $http_upgrade;
  }
}