/**
 * Schema parity verification — compares the old TypeGraphQL generated types
 * against the new Pothos SDL to detect regressions.
 *
 * Usage:
 *   cd backend && NODE_ENV=test npx dotenv-cli -e .env.development -- \
 *     npx ts-node scripts/verify-schema-parity.ts
 *
 * Reads:
 *   - /tmp/old-graphql-types.ts  (extract from: git show main:backend/src/generated/graphql.ts)
 *   - /tmp/pothos-schema.graphql (generated by scripts/export-schema.ts)
 *
 * Reports: type name differences, field differences per type, query/mutation
 * name differences, and enum value differences.
 */

import * as fs from "fs";
import { buildSchema, GraphQLEnumType, GraphQLObjectType, GraphQLInputObjectType, GraphQLNonNull, GraphQLList, GraphQLScalarType, isNonNullType, isListType } from "graphql";

// ---------------------------------------------------------------------------
// Parse the old generated graphql.ts to extract type/field info
// ---------------------------------------------------------------------------

const oldSource = fs.readFileSync("/tmp/old-graphql-types.ts", "utf-8");

interface OldTypeInfo {
  name: string;
  fields: Map<string, { nullable: boolean; type: string }>;
}

function parseOldTypes(source: string): Map<string, OldTypeInfo> {
  const types = new Map<string, OldTypeInfo>();

  // Match each "export type TypeName = { ... }" block
  // We look for non-input, non-Args, non-Resolvers types
  const typeRegex = /^export type (\w+) = \{([^}]+(?:\{[^}]*\}[^}]*)*)\};/gm;
  let match: RegExpExecArray | null;

  while ((match = typeRegex.exec(source)) !== null) {
    const typeName = match[1];

    // Skip utility types, Args types, Resolver types, input types
    if (
      typeName.endsWith("Args") ||
      typeName.endsWith("Resolvers") ||
      typeName.endsWith("Input") ||
      typeName === "Scalars" ||
      typeName === "Mutation" ||
      typeName === "Query" ||
      typeName.startsWith("Make") ||
      typeName.startsWith("Require") ||
      typeName === "Exact" ||
      typeName.startsWith("Resolvers")
    ) {
      continue;
    }

    const body = match[2];
    const fields = new Map<string, { nullable: boolean; type: string }>();

    // Match field lines: fieldName?: Maybe<Type> or fieldName: Type
    const fieldRegex = /^\s+(\w+)(\?)?:\s+(.+);/gm;
    let fieldMatch: RegExpExecArray | null;

    while ((fieldMatch = fieldRegex.exec(body)) !== null) {
      const fieldName = fieldMatch[1];
      if (fieldName === "__typename") continue;

      const isOptional = !!fieldMatch[2];
      const typeStr = fieldMatch[3].trim();
      const isMaybe = typeStr.startsWith("Maybe<");
      const nullable = isOptional || isMaybe;

      fields.set(fieldName, { nullable, type: typeStr });
    }

    if (fields.size > 0) {
      types.set(typeName, { name: typeName, fields });
    }
  }

  return types;
}

function parseOldQueryMutationFields(source: string, typeName: "Query" | "Mutation"): Set<string> {
  const fields = new Set<string>();
  const regex = new RegExp(`^export type ${typeName} = \\{([^]*?)^\\};`, "m");
  const match = regex.exec(source);
  if (!match) return fields;

  const body = match[1];
  const fieldRegex = /^\s+(\w+)[\?:]?\s*/gm;
  let fieldMatch: RegExpExecArray | null;
  while ((fieldMatch = fieldRegex.exec(body)) !== null) {
    const name = fieldMatch[1];
    if (name !== "__typename") {
      fields.add(name);
    }
  }

  return fields;
}

// ---------------------------------------------------------------------------
// Parse the new Pothos SDL schema
// ---------------------------------------------------------------------------

const sdl = fs.readFileSync("/tmp/pothos-schema.graphql", "utf-8");
const newSchema = buildSchema(sdl);

// ---------------------------------------------------------------------------
// Comparison logic
// ---------------------------------------------------------------------------

const oldTypes = parseOldTypes(oldSource);
const oldQueryFields = parseOldQueryMutationFields(oldSource, "Query");
const oldMutationFields = parseOldQueryMutationFields(oldSource, "Mutation");

const newTypeMap = newSchema.getTypeMap();
const newQueryType = newSchema.getQueryType();
const newMutationType = newSchema.getMutationType();

let issuesFound = 0;

function logDiff(category: string, message: string) {
  issuesFound++;
  console.log(`[${category}] ${message}`);
}

function logInfo(category: string, message: string) {
  console.log(`[${category}] ${message}`);
}

// --- Compare Query fields ---
console.log("\n=== QUERY FIELD COMPARISON ===\n");
const newQueryFields = new Set(
  newQueryType ? Object.keys(newQueryType.getFields()) : [],
);

// Known renames
const knownRenames: Record<string, string> = {
  comment: "commentReply", // documented intentional rename
};

for (const field of oldQueryFields) {
  const expectedNewName = knownRenames[field] || field;
  if (!newQueryFields.has(expectedNewName)) {
    logDiff("QUERY", `Missing query: ${field}${knownRenames[field] ? ` (expected as ${knownRenames[field]})` : ""}`);
  }
}

for (const field of newQueryFields) {
  // Check if it's a new query not in old (reverse of known renames)
  const reverseRenames = Object.fromEntries(
    Object.entries(knownRenames).map(([k, v]) => [v, k]),
  );
  const oldName = reverseRenames[field] || field;
  if (!oldQueryFields.has(oldName) && !oldQueryFields.has(field)) {
    logInfo("QUERY", `New query (not in old): ${field}`);
  }
}

// --- Compare Mutation fields ---
console.log("\n=== MUTATION FIELD COMPARISON ===\n");
const newMutationFields = new Set(
  newMutationType ? Object.keys(newMutationType.getFields()) : [],
);

for (const field of oldMutationFields) {
  if (!newMutationFields.has(field)) {
    logDiff("MUTATION", `Missing mutation: ${field}`);
  }
}

for (const field of newMutationFields) {
  if (!oldMutationFields.has(field)) {
    logInfo("MUTATION", `New mutation (not in old): ${field}`);
  }
}

// --- Compare Object types ---
console.log("\n=== TYPE COMPARISON ===\n");

const newObjectTypes = new Map<string, GraphQLObjectType>();
for (const [name, type] of Object.entries(newTypeMap)) {
  if (type instanceof GraphQLObjectType && !name.startsWith("__")) {
    newObjectTypes.set(name, type);
  }
}

for (const [name, oldType] of oldTypes) {
  if (!newObjectTypes.has(name)) {
    logDiff("TYPE", `Missing type: ${name}`);
    continue;
  }

  const newType = newObjectTypes.get(name)!;
  const newFields = newType.getFields();
  const oldFields = oldType.fields;

  for (const [fieldName] of oldFields) {
    if (!(fieldName in newFields)) {
      logDiff("FIELD", `${name}.${fieldName} — missing in new schema`);
    }
  }

  for (const fieldName of Object.keys(newFields)) {
    if (!oldFields.has(fieldName)) {
      logInfo("FIELD", `${name}.${fieldName} — new field (not in old)`);
    }
  }
}

for (const [name] of newObjectTypes) {
  if (name === "Query" || name === "Mutation") continue;
  if (!oldTypes.has(name)) {
    logInfo("TYPE", `New type (not in old): ${name}`);
  }
}

// --- Compare Enum types ---
console.log("\n=== ENUM COMPARISON ===\n");

// Extract enums from old source
const enumRegex = /^export enum (\w+) \{([^}]+)\}/gm;
let enumMatch: RegExpExecArray | null;
const oldEnums = new Map<string, Set<string>>();

while ((enumMatch = enumRegex.exec(oldSource)) !== null) {
  const enumName = enumMatch[1];
  const body = enumMatch[2];
  const values = new Set<string>();
  const valueRegex = /(\w+)\s*=/g;
  let valueMatch: RegExpExecArray | null;
  while ((valueMatch = valueRegex.exec(body)) !== null) {
    values.add(valueMatch[1]);
  }
  oldEnums.set(enumName, values);
}

for (const [name, type] of Object.entries(newTypeMap)) {
  if (type instanceof GraphQLEnumType && !name.startsWith("__")) {
    const oldValues = oldEnums.get(name);
    if (oldValues) {
      const newValues = new Set(type.getValues().map((v) => v.name));
      for (const val of oldValues) {
        if (!newValues.has(val)) {
          logDiff("ENUM", `${name}.${val} — missing in new schema`);
        }
      }
      for (const val of newValues) {
        if (!oldValues.has(val)) {
          logInfo("ENUM", `${name}.${val} — new value (not in old)`);
        }
      }
    }
  }
}

// --- Summary ---
console.log("\n=== SUMMARY ===\n");
if (issuesFound === 0) {
  console.log("PASS: No regressions detected.");
} else {
  console.log(`WARNING: ${issuesFound} difference(s) found. Review above for details.`);
}
