/**
 * Omitted field audit — verifies that sensitive/internal fields are NOT
 * exposed in the Pothos GraphQL schema.
 *
 * Usage:
 *   cd backend && NODE_ENV=test npx dotenv-cli -e .env.development -- \
 *     npx ts-node scripts/verify-omitted-fields.ts
 *
 * Reads: /tmp/pothos-schema.graphql (generated by scripts/export-schema.ts)
 *
 * Checks that the 17 fields listed in the migration spec are absent from
 * their respective types in the schema.
 */

import * as fs from "fs";
import { buildSchema, GraphQLObjectType, GraphQLNamedType, isNamedType, GraphQLNonNull } from "graphql";

const sdl = fs.readFileSync("/tmp/pothos-schema.graphql", "utf-8");
const schema = buildSchema(sdl);

// ---------------------------------------------------------------------------
// Fields that must NOT appear on their respective types
// ---------------------------------------------------------------------------

const omittedFields: Array<{ model: string; field: string; allowedIfType?: string }> = [
  { model: "DocumentationPage", field: "indexableContent" },
  { model: "DocumentationPage", field: "urls" },
  { model: "DocumentationPage", field: "keywords" },
  { model: "Project", field: "byPaths" },
  { model: "Project", field: "secondaryByPaths" },
  { model: "Organization", field: "preferences" },
  { model: "Ticket", field: "checklist" },
  { model: "Ticket", field: "paths" },
  { model: "Issue", field: "checklist" },
  { model: "Feature", field: "indexableContent" },
  { model: "Feature", field: "checklist" },
  { model: "Role", field: "preferences" },
  { model: "Role", field: "workWeek" },
  { model: "Product", field: "indexableContent" },
  { model: "Todo", field: "checklist" },
  { model: "User", field: "password" },
  // NOTE: User.preferences is listed in the migration spec as omitted, but
  // it WAS exposed in the old schema as a parsed UserPreferences object.
  // The raw column is omitted from prismaObject; the typed field is added
  // by a resolver. We check only that the raw String column isn't exposed.
  { model: "User", field: "preferences", allowedIfType: "UserPreferences" },
];

// ---------------------------------------------------------------------------
// Verification
// ---------------------------------------------------------------------------

let passed = 0;
let failed = 0;

console.log("=== OMITTED FIELD AUDIT ===\n");

for (const { model, field, allowedIfType } of omittedFields) {
  const type = schema.getType(model);

  if (!type) {
    console.log(`WARN: Type "${model}" not found in schema (cannot check ${field})`);
    continue;
  }

  if (!(type instanceof GraphQLObjectType)) {
    console.log(`WARN: "${model}" is not an object type (cannot check ${field})`);
    continue;
  }

  const fields = type.getFields();

  if (field in fields) {
    // Check if the field is allowed because it returns a specific typed object
    // (e.g. User.preferences returns UserPreferences, not the raw String column)
    if (allowedIfType) {
      let fieldType = fields[field].type;
      // Unwrap NonNull wrapper
      if (fieldType instanceof GraphQLNonNull) {
        fieldType = fieldType.ofType;
      }
      if (isNamedType(fieldType) && fieldType.name === allowedIfType) {
        console.log(`PASS: ${model}.${field} is exposed as ${allowedIfType} (typed object, not raw column)`);
        passed++;
        continue;
      }
    }
    console.log(`FAIL: ${model}.${field} IS exposed in the schema (should be omitted)`);
    failed++;
  } else {
    console.log(`PASS: ${model}.${field} is correctly omitted`);
    passed++;
  }
}

console.log(`\n=== SUMMARY: ${passed} passed, ${failed} failed ===`);

if (failed > 0) {
  process.exit(1);
}
