-- AlterTable
ALTER TABLE "Estimate" ADD COLUMN     "end_max" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "end_min" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "start_max" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "start_min" INTEGER NOT NULL DEFAULT 0;
